baseURL = "http://blog.314erre.rocks/"
languageCode = "en-us"
title = "314erre"
theme = "314theme"
pygmentsUseClasses =  true
pygmentsCodeFences = true

[params]
    description = "My site description"
    author = "Pierre"
    subtitle = "IT student"
[[menu.main]]
    name = "About"
    url = "/about"

[[menu.main]]
    name = "Blog"
    url = "/blog"
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/"
    pre = "<i class='fab fa-github'></i>"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/"
    pre = "<i class='fab fa-twitter'></i>"
[[menu.social]]
    name = "Root-me"
    url = "https://www.root-me.org/Pierre-44221/"
    pre = "<i class='fas fa-skull'></i>"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4